[variables]
    NIXPACKS_PHP_VARIANT = 'pypa'

[phases.setup]
    nixPkgs = ['php74', 'php74Extensions.pdo_pgsql', 'php74Extensions.pgsql', 'php74Extensions.gd', 'php74Extensions.zip', 'nodejs']

[phases.install]
    cmds = ['composer install --ignore-platform-reqs']

[start]
    cmd = 'php -S 0.0.0.0:$PORT index.php'
